dist: xenial
language: python
python:
  - 3.6
  - 3.5

before_install:
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r web/requirements.txt
  - pip install flake8

script: 
  - python web/manage.py test
  - flake8
