# Generated by Django 2.1 on 2018-09-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, null=True),
        ),
    ]
