# Generated by Django 2.1.1 on 2018-09-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20180901_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
