# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20180926_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
