# Generated by Django 2.1.1 on 2018-10-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_product_minimum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('.blue', '.blue'), ('.green', '.green'), ('.yellow', '.yellow'), ('.orange', '.orange'), ('.purple', '.purple'), ('.black', '.black')], default='.blue', max_length=10),
        ),
    ]
