# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20160525_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_totalprice',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
