# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import pos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20160527_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, validators=[pos.models.validate_product_name]),
        ),
    ]
