# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
